ToDoList/Models/Category.cs
using System.Collections.Generic;

namespace ToDoList.Models
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public List<Item> Items { get; set; }
    }
}

ToDoList/Models/Item.cs
using System.Collections.Generic;
using MySqlConnector;

namespace ToDoList.Models
{
  public class Item
  {
    public int ItemId { get; set; }
    public  string Description{ get; set; }

     public int CategoryId { get; set; }
        public Category Category { get; set; }

  }
}

ToDoList/Models/ToDoListContext.cs
using Microsoft.EntityFrameworkCore;

namespace ToDoList.Models
{
  public class ToDoListContext : DbContext
  {
    public DbSet<Category> Categories { get; set; }
    public DbSet<Item> Items { get; set; }

    public ToDoListContext(DbContextOptions options) : base(options) { }
  }
}

ToDoList/Controllers/CategoriesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using System.Collections.Generic;
using System.Linq;

namespace ToDoList.Controllers
{
  public class CategoriesController : Controller
  {
    private readonly ToDoListContext _db;

    public CategoriesController(ToDoListContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Category> model = _db.Categories.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Category category)
    {
      _db.Categories.Add(category);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Category thisCategory = _db.Categories
                                  .Include(category => category.Items)
                                  .FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    public ActionResult Edit(int id)
    {
      Category thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    [HttpPost]
    public ActionResult Edit(Category category)
    {
      _db.Categories.Update(category);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Category thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Category thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      _db.Categories.Remove(thisCategory);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

ToDoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }
     
  }

    }

ToDoList/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using System.Collections.Generic;
using System.Linq;

namespace ToDoList.Controllers
{
  public class ItemsController : Controller
  {
    private readonly ToDoListContext _db;

    public ItemsController(ToDoListContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Item> model = _db.Items
                            .Include(item => item.Category)
                            .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Item item)
    {
      if (item.CategoryId == 0)
      {
        return RedirectToAction("Create");
      }
      _db.Items.Add(item);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Item thisItem = _db.Items
                          .Include(item => item.Category)
                          .FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }

    public ActionResult Edit(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisItem);
    }

    [HttpPost]
    public ActionResult Edit(Item item)
    {
      _db.Items.Update(item);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      _db.Items.Remove(thisItem);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

ToDoList/Views/Categories/Create.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category

<h4>Add a new category</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new category" />
}
<p>@Html.ActionLink("Show all categories", "Index")</p>

ToDoList/Views/Categories/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

ToDoList/Views/Categories/Details.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category
@using ToDoList.Models

<h2>Category Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>

@if (@Model.Items.Count == 0)
{
  <h3>No items have been added to this category yet!</h3>
} 
else
{
  <h3>Items:</h3>
  <ul>
    @foreach (Item item in Model.Items)
    {
      <li>@Html.ActionLink($"{item.Description}", "Details", "Items", new { id = item.ItemId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Edit Category", "Edit", new { id = Model.CategoryId })</p>
<p>@Html.ActionLink("Delete Category", "Delete", new { id = Model.CategoryId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Categories/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CategoryId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Categories/Index.cshtml
@{
  Layout = "_Layout";
}

@using ToDoList.Models;

<h1>Categories</h1>

@if (@Model.Count == 0)
{
  <h3>No categories have been added yet!</h3>
} 

<ul>
  @foreach(Category category in Model)
  {
    <li>@Html.ActionLink($"{category.Name}", "Details", new { id = category.CategoryId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new category", "Create")</p>
<p>@Html.ActionLink("Add new Item", "Create", "Items")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

ToDoList/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the To Do List!</h1>
<p>@Html.ActionLink("See all items", "Index", "Items")</p> 

<p>@Html.ActionLink("Home", "Index", "Home")</p>

ToDoList/Views/Items/Create.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category

<h4>Add a new category</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new category" />
}
<p>@Html.ActionLink("Show all categories", "Index")</p>

ToDoList/Views/Items/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

ToDoList/Views/Items/Details.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category
@using ToDoList.Models

<h2>Category Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>

@if (@Model.Items.Count == 0)
{
  <h3>No items have been added to this category yet!</h3>
} 
else
{
  <h3>Items:</h3>
  <ul>
    @foreach (Item item in Model.Items)
    {
      <li>@Html.ActionLink($"{item.Description}", "Details", "Items", new { id = item.ItemId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Edit Category", "Edit", new { id = Model.CategoryId })</p>
<p>@Html.ActionLink("Delete Category", "Delete", new { id = Model.CategoryId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Items/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CategoryId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Items/Index.cshtml
@{
  Layout = "_Layout";
}

@using ToDoList.Models;

<h1>Categories</h1>

@if (@Model.Count == 0)
{
  <h3>No categories have been added yet!</h3>
} 

<ul>
  @foreach(Category category in Model)
  {
    <li>@Html.ActionLink($"{category.Name}", "Details", new { id = category.CategoryId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new category", "Create")</p>
<p>@Html.ActionLink("Add new Item", "Create", "Items")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

ToDoList/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My To-Do List!</title>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>